apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority-data: "${cluster_ca_certificate}"
    server: "https://${endpoint}"
users:
- name: default
  user:
    token: "${token}"
contexts:
- name: default
  context:
    cluster: default
    user: default
current-context: default
