apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
- namespace.yaml
- grafana-pvc.yaml
- grafana-deployment.yaml
- service.yaml
- secret.yaml

configMapGenerator:
- name: datasources
  files: [ provisioning/datasources/default.yaml ]

- name: dashboards
  files: [ provisioning/dashboards/default.yaml ]

- name: dashboards-pods-cluster-2
  files:
    - provisioning/dashboards/cluster-2/pod.json

- name: dashboards-pods-cluster-3
  files:
    - provisioning/dashboards/cluster-3/pod.json
    
- name: dashboards-infra
  files:
    - provisioning/dashboards/infra/nodes.json
  
