apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-service.prometheus-federation.svc.cluster.local:8080
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: PASSWORD

      