apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
- namespace.yaml
- config-maps.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
