have_fun: true
code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
  pull_request_reopened:
    help: false
    summary: false
    code_review: false
  pull_request_closed:
    help: false
    summary: false
    code_review: false
  pull_request_merged:
    help: false
    summary: false
    code_review: false
ignore_patterns: []
#